name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch
        tag_prefix: 'v'  # Set to 'v' since your tags have 'v' prefix
        create_annotated_tag: true

    - name: Output New Version and Tag
      run: |
        echo "New Version: ${{ steps.tag_version.outputs.new_version }}"
        echo "New Tag: ${{ steps.tag_version.outputs.new_tag }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USER }}/vllm-huggingface:latest
          ${{ secrets.DOCKER_USER }}/vllm-huggingface:${{ steps.tag_version.outputs.new_version }}
